### ISSUE TITLE
adding testID for props

### ISSUE THREAD

**Issue by mohammadalijf** [alantoa/react-native-awesome-slider#11]
Hello thank you for your awesome slider.

I was wonder if it is possible to add testID on the slider component?

**Comment by alantoa** [comment]
Hi, @mohammadalijf!
sure, but I'm busy now, that's great if you commit a PR for this lib!

**Comment by mohammadalijf** [comment]
created a PR that also has this #14

**Comment by alantoa** [comment]
https://github.com/alantoa/react-native-awesome-slider/issues/12
Thank you!
