### ISSUE TITLE
after layout, changing step, minimum, maximum value does not has effect on component

### ISSUE THREAD

**Issue by mohammadalijf** [alantoa/react-native-awesome-slider#12]
Most of calculations are happening onLayout handler in component. after layout if we change step, minimumValue, maximumValue component would not show correct values and behaviours.

one work around is to set `keys` with relative props so it would force to trigger onLayout.

```
<Slider
      /**
       * This key is needed here though it looks useless.
       * slider library calculate values on layout...
       * to enforce the slider to calculate new values we need to pass this key so it would update itself when step or maximumValue or minimumValue changes
       */
      key={`${step}${wrapperMaximumValue}${wrapperMinimumValue}`}
      ... />
```

**Comment by alantoa** [comment]
Hi, @mohammadalijf
Thank you for your feedback, If this solves your problem you are very welcome to submit a PR. and I will release a version later, very thanks!

**Comment by mohammadalijf** [comment]
created a PR that also has this #14

**Comment by alantoa** [comment]
@mohammadalijf 
Published to npm: https://www.npmjs.com/package/react-native-awesome-slider
