### ISSUE TITLE
onStartSliding 

### ISSUE THREAD

**Issue by jay-jlm** [alantoa/react-native-awesome-slider#2]
![image](https://user-images.githubusercontent.com/21344963/153265029-b1cbd206-b18e-48be-b05c-c509a3c89482.png)

**Expected Behavior**
 
Declaring `onSlidingStart`  should not be required. 

**Current Behavior**

Typescript complains of missing property if `onSlidingStart` is left undeclared.

**Comment by alantoa** [comment]
Hi, I'm fixed this. 
It's been released.
Thanks!
