### ISSUE TITLE
Minimum track tint as gradient

### ISSUE THREAD

**Issue by Bieluu** [alantoa/react-native-awesome-slider#21]
Hi @alantoa 

Is there any way to render minimum track as linear gradient?

![Screenshot 2022-06-23 at 17 48 42](https://user-images.githubusercontent.com/35278190/175341496-1a40e99e-a63a-4745-8d06-96c9a75ff092.png)

**Comment by alantoa** [comment]
@Bieluu Hi!
It's not supported yet, but it's a great idea!
I'll try to implement it when I have time, or you can fork this lib, use `LinearView` replace to `MinimumTrackView`.

**Comment by Bieluu** [comment]
Will do. Thank you for this awesome package 😄
