### ISSUE TITLE
How to use this module with react-native-track-player?

### ISSUE THREAD

**Issue by suupham2506** [alantoa/react-native-awesome-slider#23]
I can not update the progress sync with the audio progress? Any help?

**Comment by alantoa** [comment]
[this docs](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedProps/) can help you.

**Comment by alantoa** [comment]
https://github.com/alantoa/react-native-awesome-slider/issues/26#issue-1383474867
the man has an example, I think should help you!

**Comment by ser-emejia** [comment]
> I can not update the progress sync with the audio progress? Any help?

Hey man, did you find a solution?
