### ISSUE TITLE
Bug: Slider is not working on Android

### ISSUE THREAD

**Issue by cavishek39** [alantoa/react-native-awesome-slider#25]
### Description:
When I am going to place the component after passing the required props, it is not sliding at all.

**Comment by alantoa** [comment]
are you following the [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation) and [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation)'s docs?
