### ISSUE TITLE
Vertical

### ISSUE THREAD

**Issue by maartenvandillen** [alantoa/react-native-awesome-slider#3]
Hi can you add a vertical prop to make a vertical slider?

**Comment by alantoa** [comment]
Ye, @maartenvandillen   I need a moment, wait for me.

**Comment by alantoa** [comment]
I think you can use style to vertical. @maartenvandillen 
Example code:
```
 <Slider style={[
      styles.container,
      {
        transform: [
          {
            rotate: '90deg',
          },
        ],
      },
    ]}
    progress={progress5}
    minimumValue={min}
    maximumValue={max}
    minimumTrackTintColor="#FFAB76"
    maximumTrackTintColor="#FFEEAD"
  />
```

**Comment by maartenvandillen** [comment]
transforms are only visual. Does that work ok with the gesture handler?

**Comment by alantoa** [comment]
It's ok, I tried, but you may need to adjust the position.
![截屏2022-02-12 上午12 58 08](https://user-images.githubusercontent.com/37520667/153634908-90c915ce-ab11-4a26-8b7a-43b582bd991a.png)

**Comment by maartenvandillen** [comment]
Thanks for looking into this. I just realised I need to upgrade to reanimated v2 and use the Hermes engine on Android. Are those two ready for production? My last experience with Hermes was a SIGFAULT error on app startup so I stayed clear from it for a while.

**Comment by alantoa** [comment]
Yes, I‘ve been using Hermes since `react-native 0.64+`, hermes engine is awesome. If you encounter any problems using Hermes there are solutions.

**Comment by alantoa** [comment]
Hi, @maartenvandillen If there is no problem, I will close this Issue, thank you!
