### ISSUE TITLE
Not working with reanimated v2.13.0

### ISSUE THREAD

**Issue by grgmgd** [alantoa/react-native-awesome-slider#32]
**Description:**
Upgraded from reanimated 2.8.0 to 2.13.0 slider no longer works. Thumb stopped moving and the slider stays at the initial value. Bubble still visible and moves with the gesture, so I am guessing its a compatibility issues with the new reanimated version.

**Comment by efstathiosntonas** [comment]
@grgmgd is this happening after you move the thumb with the finger? 

@alantoa I think I'm having a similar issue (I'm also using reanimated `2.13.0`), when the audio file plays, the thumb moves just fine but when I start sliding the thumb the moment I release it and the playback resumes the thumb won't follow the track.

**Comment by layerok** [comment]
@efstathiosntonas it seems you are describing #29

**Comment by alantoa** [comment]
thanks for the feedback, let me check it.

**Comment by alantoa** [comment]
@grgmgd I have already upgrade reanimated version to v3 in example project, i didn't see these error, so closed it.
