### ISSUE TITLE
Slider not updated when sharedValue.value is updated

### ISSUE THREAD

**Issue by Julienblc** [alantoa/react-native-awesome-slider#37]
Hello !

I have something weird in a project. I have a slider, with answers just upon it. When I change the value of the slider, the answers's style is well updated. But when I press an answer, which call the update of the shareValue.value, the slider si not updated.

I've created a repo if you want to check on your computer : https://github.com/Julienblc/test-slider

Here is a video to show the behaviour : 

https://user-images.githubusercontent.com/7222986/224650757-02c8333a-98d1-4a91-ac09-af786dbb8362.mov

What have I done wrong ?

**Comment by efstathiosntonas** [comment]
Hi @Julienblc can you try downgrading to 2.1.3 and see if works as expected?

**Comment by Julienblc** [comment]
Oh nice, it's working with 2.1.3
What is breaking change that broke that ?

**Comment by Julienblc** [comment]
I found a new bug that seems to be linked : if i change the value by clicking on the slider THEN i click on answer, the slider is not changed.
Tested with 2.1.3


https://user-images.githubusercontent.com/7222986/224721882-6f1e4b51-fe92-4a83-8f41-b1797abd8137.mov

**Comment by alantoa** [comment]
@Julienblc Sorry for being late because I missed the last comment before!
is it in this example? 
https://github.com/Julienblc/test-slider/blob/main/App.js

**Comment by Julienblc** [comment]
@alantoa No problem !
Yes the issue is in this example

**Comment by alantoa** [comment]
@Julienblc hi, i just fixed it in https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.4.1 

https://github.com/alantoa/react-native-awesome-slider/assets/37520667/60917db1-6bb1-4b5f-b55c-19d5f58ebecd

**Comment by Julienblc** [comment]
Thank you @alantoa  ! 👏 💪
