### ISSUE TITLE
Add step prop

### ISSUE THREAD

**Issue by jared-94** [alantoa/react-native-awesome-slider#4]
Thanks for your great package!

As many other sliders it would be nice to have a `step` prop (for a discrete slider)

**Comment by alantoa** [comment]
Ok, I will add this feature later.You can follow this lib.

**Comment by jared-94** [comment]
Thanks 👍

**Comment by alantoa** [comment]
@jared-94  Hi, I have added step feature, [See example](https://github.com/alantoa/react-native-awesome-slider/blob/main/example/src/screens/home.tsx), you just use code:
```jsx
<Slider
    progress={progress}
    minimumValue={min}
    maximumValue={max}
    step={10}
/>
```
Regrettably, I was busy, just simply did a test, I hope you can help me test it out.
If you have any questions, welcome to call me.
Finally, if you think it's good, please give me a Star, Thank you!

**Comment by jared-94** [comment]
Thanks It works fine !

However, it seems that `onSlidingComplete` doesn't return the correct value...
Any idea?

**Comment by alantoa** [comment]
@jared-94  This is a bug, I will deal with it asap

**Comment by alantoa** [comment]
@jared-94 Hi, I fixed it! 
You can try it!
