### ISSUE TITLE
Silder into modal on Android not working

### ISSUE THREAD

**Issue by dngns** [alantoa/react-native-awesome-slider#44]
Hi @alantoa, I trying to put silder into modal but on android can not drag
im using this code on expo project with these library react-native-modal ^13.0.1 and react-native-awesome-slider ^2.4.2 
[SliderNotWorking.webm](https://github.com/alantoa/react-native-awesome-slider/assets/80993895/ff3ddca8-5e0d-46f2-afdb-290f3b7cd372)
 
My code there 
![image](https://github.com/alantoa/react-native-awesome-slider/assets/80993895/8aec5cc9-a2b8-4b03-8775-63c98508f488)

**Comment by alantoa** [comment]
Hey, @ducnguyen4301, please check out [this document](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#usage-with-modals-on-android) and follow the installation instructions for Android.

**Comment by dngns** [comment]
> 

thanks for issue.
