### ISSUE TITLE
On initial render, progress shows incorrect value when `step` is set

### ISSUE THREAD

**Issue by yayanartha** [alantoa/react-native-awesome-slider#46]
When running the example app, I noticed the slider progresses on the initial render are incorrect when the `<Slider>` has `step={10}` or `step={6}`. If I comment out those steps, they will show correctly on the initial render.

**Comment by yeesiang95** [comment]
I also facing this issue, initial value is incorrect when set step value

**Comment by yayanartha** [comment]
as I am still using reanimated v2, downgrading to `2.3.0` solves the issue for me

**Comment by yeesiang95** [comment]
> as I am still using reanimated v2, downgrading to `2.3.0` solves the issue for me

Ok, will try to downgrade. Thanks!

**Comment by alantoa** [comment]
Thanks for all of your feedback! I have just merged @computerjazz's PR and did a tiny improment, and i have also released a new version [here](https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.4.5)!

**Comment by Nero15739** [comment]
This seems to still be an issue when using RN Reanimated V3.5.4. Was this fixed or should I be downgrading to V2? @alantoa
