### ISSUE TITLE
Does this library support two thumb range selector?

### ISSUE THREAD

**Issue by badalsaibo** [alantoa/react-native-awesome-slider#50]
![Screenshot 2023-11-08 at 4 39 19 PM](https://github.com/alantoa/react-native-awesome-slider/assets/14058003/e1d38865-e8ac-4479-9527-ef5cc1f28b3c)

**Comment by antoinerousseau** [comment]
same question here, @badalsaibo how did you implement it in the end?

**Comment by badalsaibo** [comment]
@antoinerousseau I used `rn-range-slider` library to implement.
