### ISSUE TITLE
isScrubbing is not set to false when tapping on the slider or thumb

### ISSUE THREAD

**Issue by techfoundrynz** [alantoa/react-native-awesome-slider#54]
The isScrubbing value is set to true and never false again when tapping on the slider. This makes styling the slider based on the current interaction state unreliable.

It appears that the issue is that the tap even gesture only sets the values to true and never false again. I would expect it to either set the value to false, or set the value to true, then to false again on a delay. (After some testing, I would recommend no delay)

The current workaround is to manually update the value yourself by passing an onSlidingComplete function but keeping that manually updated defeats the purpose of providing a value.

![image](https://github.com/alantoa/react-native-awesome-slider/assets/13304863/69355255-8b3a-46a3-8381-6107502de694)

**Comment by alantoa** [comment]
hey, thanks for the feedback, this issue should have been fixed in v2.6.4.
