### ISSUE TITLE
The value of the progress bar is not refreshing.

### ISSUE THREAD

**Issue by caner219** [alantoa/react-native-awesome-slider#60]
When setting the value of progress for the first time, it takes effect. However, when I retrieve data from the server and want to display it on the progress bar, the progress does not refresh. How can I solve this issue?

**Comment by caner219** [comment]
![1708333166028](https://github.com/alantoa/react-native-awesome-slider/assets/19943393/9613d783-6186-4661-a074-6ee290adf7b0)

**Comment by alantoa** [comment]
Can you please follow the example and give it a try?

```tsx
export const Example = () => {
  const progress = useSharedValue(30);
  const min = useSharedValue(0);
  const max = useSharedValue(100);
  return (
    <Slider
      style={styles.container}
      progress={progress}
      minimumValue={min}
      maximumValue={max}
    />
  );
};
```

**Comment by caner219** [comment]
I made the changes as you suggested, but the progress bar's progress is still not refreshing. The printed value of "progressValue called with = " is changing, but the progress bar itself is still not changing.
![截屏2024-02-21 上午9 50 55](https://github.com/alantoa/react-native-awesome-slider/assets/19943393/3a97d9f0-939b-4dd9-bde8-eed36baf9edb)

**Comment by alantoa** [comment]
>but the progress bar's progress is still not refreshing. 

Are you saying that you have already dragged the thumb, but the slider did not change at all?

**Comment by caner219** [comment]
When I manually drag the progress bar, that works fine. The problem is when I get the data from the server and then go to set the progress value, the progress value changes but the progress bar UI does not refresh, it stays at the initial value it was set to.

**Comment by amalpsojancodiac** [comment]
maybe this will help you :)

```js
export const Example = () => {
const progress = useSharedValue(30);
 const min = useSharedValue(0);
 const max = useSharedValue(100);
  return (
    <Slider
      style={styles.container}
      progress={progress}
      minimumValue={min}
      maximumValue={max}
      cache={progress}
    />
  );
};
```

**Comment by caner219** [comment]
Hi，I made the modifications as you instructed, but the UI of progress still has not refreshed.

**Comment by caner219** [comment]
![截屏2024-02-26 下午4 44 53](https://github.com/alantoa/react-native-awesome-slider/assets/19943393/eceba6b8-1827-45c8-8170-3004c35d7dc8)
![截屏2024-02-26 下午4 45 10](https://github.com/alantoa/react-native-awesome-slider/assets/19943393/97a0d918-cad6-4148-a862-8b4f62af26ea)

**Comment by manuelxaguilar** [comment]
@caner219  Any luck with this?

**Comment by TikshaK** [comment]
I am facing the same issue.... anyone found the solution?

**Comment by alantoa** [comment]
@caner219, doesn't it work for you if you set the `progress` SharedValue? Typically, if you only want to change the progress value, you can simply do `progress.value = number;`.

**Comment by domalouf** [comment]
I had a similar issue when trying to use the Slider inside a modal. I couldn't get the progress spot to change based on parameters passed into the modal. I think it has something to do with useSharedValue variables updating asynchronously.

Here is a link to the documentation (the first code block under remarks is where the problem comes from I think), [https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue/](https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue/)

**Comment by nrcaz** [comment]
Having the same problem here, you can just repro the issue with a button setting the sharedValue in progress. It does not update the slider.

**Comment by glairnarra31** [comment]
Can confirm the bug occurs when snapToStep is set to true

**Comment by fform** [comment]
Had this same problem. In the meantime, an easy fix is to force the whole component to re-render if you are setting the progress from somewhere else. Easiest way to do that is change the key. So
```js
const progress = useSharedValue(0);
useEffect(()=>{
   progress.value = outsideValue;
}, [outsideValue]);
...
<Slider
  key={`slider-${outsideValue}`}
  steps={stepsSV}
/>
```

The key can be whatever but just making a new key forces a full unmount/remount instead of the managed internal state not picking up the new `outsideValue`

**Comment by Aklile-Yilma** [comment]
> Had this same problem. In the meantime, an easy fix is to force the whole component to re-render if you are setting the progress from somewhere else. Easiest way to do that is change the key. So
> 
> ```js
> const progress = useSharedValue(0);
> useEffect(()=>{
>    progress.value = outsideValue;
> }, [outsideValue]);
> ...
> <Slider
>   key={`slider-${outsideValue}`}
>   steps={stepsSV}
> />
> ```
> 
> The key can be whatever but just making a new key forces a full unmount/remount instead of the managed internal state not picking up the new `outsideValue`

Thanks this worked for me. The key prop is necessary to force react to re-render.

`
                {
                  userSettings?.storage_months && (
                    <View style={Styles.sliderMainWrap}>
                      <UISlider key={userSettings?.storage_months} handleSliderChange={handleSliderChange} defaultValue={parseInt(userSettings?.storage_months!)}/>
                    </View>
                  )
                }
`

`
import Colors from "@/Src/Styles/Colors";
import { View } from "react-native";
import { Slider } from "react-native-awesome-slider";
import { useSharedValue } from "react-native-reanimated";
import Styles from "./Styles";
import { useEffect } from "react";

interface UISliderProps {
    defaultValue: number,
    handleSliderChange: any
}
const UISlider = ({handleSliderChange, defaultValue}: UISliderProps) => {
    const progress = useSharedValue(defaultValue);
    const min = useSharedValue(1);
    const max = useSharedValue(12);

    useEffect(() => {
        progress.value = defaultValue;
    }, [defaultValue]);

    console.log("progress", progress.value, )

    return (
        <Slider
          containerStyle={{ borderRadius: 8 }}
          progress={progress}
          minimumValue={min}
          maximumValue={max}
          theme={{
            maximumTrackTintColor: Colors.White,
            minimumTrackTintColor: Colors.Blue,
            bubbleTextColor: Colors.White,
            bubbleBackgroundColor: Colors.Blue,
          }}
          sliderHeight={12}
          steps={11}
          snapToStep={true}
          style={Styles.sliderWrap}
          markStyle={{backgroundColor: "transparent"}}
          onSlidingComplete={(value) => {
            progress.value = value;
            handleSliderChange('storageMonths', value.toString())
          }}
        />
    )
}


export default UISlider
`

**Comment by alantoa** [comment]
I added an example here, please check [this example](https://github.com/alantoa/react-native-awesome-slider/blob/main/example/src/sample/src/binance-slider.tsx) to solve the problem you encountered. 

and be sure you have updated the last version, btw.
