### ISSUE TITLE
React not defined

### ISSUE THREAD

**Issue by MathiasSvDK** [alantoa/react-native-awesome-slider#61]
When using web React is not defined in lib/module/ballon.js.
You use the function React but its not imported at line 1.

Its:
import { forwardRef, useImperativeHandle, useRef, memo } from 'react';

But should be:
import React, { forwardRef, useImperativeHandle, useRef, memo } from 'react';

**Comment by alantoa** [comment]
Hey @MathiasSvDK, It seems like this is related to your TypeScript issue. Could you please check if it's connected to your project setup?

**Comment by MathiasSvDK** [comment]
I dont have typescript on it. My buddy has a typescript project tho and it doesnt work for him either

**Comment by MathiasSvDK** [comment]
We both fixed it by adding it tho

**Comment by alantoa** [comment]
got it, i just added React on that file in [v2.5.1](https://www.npmjs.com/package/react-native-awesome-slider), let's see if it fixed your issue.

**Comment by MathiasSvDK** [comment]
Works now for both of us without having to modify it. 
Update worked.
