### ISSUE TITLE
Only allow drag input if user is holding onto the thumb

### ISSUE THREAD

**Issue by rageshoo** [alantoa/react-native-awesome-slider#63]
Right now, I can press anywhere along the slider. The thumb will move to where I pressed and follow as I drag along the slider.

I want to only allow dragging if the user presses on the thumb first, before dragging. Is this possible to achieve?

**Comment by alantoa** [comment]
Can you please try setting `disableTapEvent={false}` on the slider?

**Comment by rageshoo** [comment]
> Can you please try setting `disableTapEvent={false}` on the slider?

Setting 'disableTapEvent={true}' fixes it partially. I can no longer tap to random spots along the slider.

However, if I tap on any random spot on the slider and drag, the thumb will jump and follow the drag.

I only want the thumb to move if I touch it first then drag.

**Comment by alantoa** [comment]
I added properties `disableTrackPress` and `thumbTouchSize` to support it, please update to the latest version [v2.6.5](https://www.npmjs.com/package/react-native-awesome-slider/v/2.6.5).

If you want to see an example, please refer to the code [here](https://github.com/alantoa/react-native-awesome-slider/blob/main/example/src/sample/src/binance-slider.tsx).
