### ISSUE TITLE
Slider is not interactive, can't move it

### ISSUE THREAD

**Issue by nerminba** [alantoa/react-native-awesome-slider#65]
I followed the simple instructions on this page: https://www.npmjs.com/package/react-native-awesome-slider

I'm using expo sdk v50, I've installed  everything according to instructions on above page, to quickly get going I've just added this in my app:

```
import { useSharedValue } from 'react-native-reanimated';
import { Slider } from 'react-native-awesome-slider';

export const Example = () => {
  const progress = useSharedValue(30);
  const min = useSharedValue(0);
  const max = useSharedValue(100);
  return (
    <Slider
      style={styles.container}
      progress={progress}
      minimumValue={min}
      maximumValue={max}
    />
  );
};

```
and also wrapped at relevant place with GestureHandlerRootView.

Finally the Slider would render on my device (Pixel 7 Pro) without errors, but now while it looks "awesome", it's dead, nothing happens when I try to pull it. And I have no clue if its a bug or something else.

![app](https://github.com/alantoa/react-native-awesome-slider/assets/443080/8e1ffed2-7275-4a0f-95a3-5218846b002b)

**Comment by nerminba** [comment]
Solved

**Comment by Ilansuli** [comment]
> Solved

what was the soultion? its happening for me too

**Comment by periakteon** [comment]
same.

@nikocraft can you explain how you solved this?

**Comment by nerminba** [comment]
Sorry guys I forgot how I solved it. I usually share my solutions when I close the ticket, but I forgot to do it this time. If one of you figures it out, do not forget to share it here for the others! :)
