### ISSUE TITLE
Slider don't show progress when is disable

### ISSUE THREAD

**Issue by ser-emejia** [alantoa/react-native-awesome-slider#66]
Hello, first of all, thank you for your work on this, is amazing!

I have an issue, when I add the prop `disable` the slider does not show the current progress, Am I missing something?

```
import { Slider } from 'react-native-awesome-slider';

<Slider
    disable={true}
    minimumValue={min}
    maximumValue={max}
    progress={progress}
    thumbWidth={0}
    renderBubble={() => null}
    heartbeat={bufferingDuringPlay}
 />
```

**Comment by alantoa** [comment]
Hey, have you checked what happens if you set `disableMinTrackTintColor`?
```
<Slider
  theme={{
    disableMinTrackTintColor: '#fff',
    maximumTrackTintColor: '#fff',
    minimumTrackTintColor: '#000',
    cacheTrackTintColor: '#333',
    bubbleBackgroundColor: '#666',
    heartbeatColor: '#999',
  }}
/>
```

**Comment by alantoa** [comment]
I assume that the progress is being updated, but the color is the same as the track bar color.
lmk if it doesn't work

**Comment by ser-emejia** [comment]
> I assume that the progress is being updated, but the color is the same as the track bar color. lmk if it doesn't work

It works! Thank you :)
