### ISSUE TITLE
Fatal Error with latest version of Reanimated

### ISSUE THREAD

**Issue by Bayramito** [alantoa/react-native-awesome-slider#73]
When I upgrade the reanimated from 3.8.1 to 3.11, i get following fatal error

![simulator_screenshot_52748102-9613-4277-82B1-383B6E7D0E15](https://github.com/alantoa/react-native-awesome-slider/assets/44513402/8f358cb5-7361-49b5-b023-e45b332b0839)

**Comment by alantoa** [comment]
hey @Bayramito, thank you for the report. I will test it out now!

**Comment by alantoa** [comment]
![CleanShot 2024-05-14 at 17 33 12@2x](https://github.com/alantoa/react-native-awesome-slider/assets/37520667/59923720-73f4-4411-84ca-5afe9f2a100c)
It actually works for me. I just updated the example project. Can you try that [example project](https://github.com/alantoa/react-native-awesome-slider/tree/main/example) to see if it works for you?

**Comment by Bayramito** [comment]
Yes i just tested with the latest version it works fine.. Thank you so much
