### ISSUE TITLE
The cursor moves in reverse

### ISSUE THREAD

**Issue by Muhamad-tech** [alantoa/react-native-awesome-slider#75]
When I move the slider, **it moves in the opposite direction**, the emulator language is **Arabic** but when I switch the language back to English, everything works fine.

React native **[0.73.4]**
Android API **[34]**
react-native-awesome-slider **[2.5.3]**

https://github.com/alantoa/react-native-awesome-slider/assets/165002902/dbac982e-9d85-4ce5-9853-3ad624939407

**Comment by AhmadAl-Ghalban** [comment]
i have same issue

**Comment by alantoa** [comment]
can you plz add a example code for that?

**Comment by alantoa** [comment]
oh sorry, I haven't added RTL support yet.

**Comment by mrkarimi2001** [comment]
@alantoa Hello, I hope you are great. How long does it take to add the RTL support?

**Comment by alantoa** [comment]
I'll try, man!

**Comment by alantoa** [comment]
https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.8.0
just added in v2.8.0, check it out!
