### ISSUE TITLE
Issue with modal in android.

### ISSUE THREAD

**Issue by vishaljnimblechapps** [alantoa/react-native-awesome-slider#80]
This Caused re-render in android when use with modal. Please see attach video.

https://github.com/user-attachments/assets/115b7d3a-635d-47c7-b2ed-cfd16634578f

**Comment by AndrRomanenko** [comment]
@vishaljnimblechapps 
Try to wrap your modal content with useMemo

```
const Content = useMemo(
    () =>
       // gestureHandlerRootHOC to work properly on Android
      gestureHandlerRootHOC(() => (
        <View>
        .....
        </View>
     )), 
    []
   );
   
   return (
   <Modal>
     <Content />
   </Modal>
   )
   ```

**Comment by alantoa** [comment]
@vishaljnimblechapps sorry very delay responding, it seems a memo issue.

**Comment by alantoa** [comment]
I cannot repro it, it's best to update to the latest version and try it because I have fixed some issues. 
If it still happens, please let me know and create a minimal example.
