### ISSUE TITLE
Bubble strips trailing 0s and if progress updates while user is sliding it overrides the bar

### ISSUE THREAD

**Issue by switz** [alantoa/react-native-awesome-slider#85]
If I return "4:40" in bubble it only renders "4:4".

And if the user is dragging the slider, but `progress.value` updates, it will flicker back and forth. It should ignore progress updates _while_ the user is dragging.

Happy to send a PR if it will get merged for both.

Thanks!

**Comment by alantoa** [comment]
hey, creating a RP would be great! or I'll look into it when I have time. :)

**Comment by alantoa** [comment]
@switz  does this custom bubble text render not work?  

``` tsx
bubble={(s: number) => {
  return formatAnyText(s);
}}
```

**Comment by switz** [comment]
yeah it doesn't work, it strips the 0s

**Comment by alantoa** [comment]
can you share the code? sorry, I don't really understand what your needs are.

**Comment by alantoa** [comment]
Oh, I see. Perhaps this is caused by the `TextInput` component. In this case, I think you can use `renderBubble` to customize its rendering bubble. 

```tsx
const [text, setText] = useState(``);
bubble={(s) => {
  setText(`${s}`);
  return ``;
}}
renderBubble={() => <Text>{text}</Text>}
```

**Comment by alantoa** [comment]
The reason for using `TextInput` as the default bubble is for performance considerations, because repeated changes in text will cause local rendering, while `TextInput` only needs to directly set the `value` prop without using state control.
