### ISSUE TITLE
Slider doesn't behave as expected when progress value is changed programmatically

### ISSUE THREAD

**Issue by romin-backpack** [alantoa/react-native-awesome-slider#87]
When changing the progress value programmatically, the slider doesn't behave as expected:
- The thumb doesn't move
- If we drag the thumb manually, the other thumbs don't change color even when we go past them

I made an [expo snack](https://snack.expo.dev/@romin-backpack/using-react-native-awesome-slider) that uses your Binance example to show the problem. The only change is the `TextInput` that was added, and the `useEffect` that changes the progress value. 

https://github.com/user-attachments/assets/08a2220f-2f0c-418f-8b2b-d3a3556fd031

**Comment by alantoa** [comment]
hey @romin-backpack, you can just remove the `useEffect` code and then use `useAnimatedReaction` instead.

the code will be like:

```
  // useEffect(() => {
  //   progress.value = value;
  // }, [value]);


  useAnimatedReaction(
    () => {
      return value;
    },
    (data) => {
      if (data !== undefined && !isNaN(data)) {
        progress.value = data;
      }
    },
    [value]
  );
```

that's just sample code, may need to handle some error boundary cases for the text input.

**Comment by romin-backpack** [comment]
Hi @alantoa that's very helpful. I am running the example app now but it seems that on the Binance example, when I set `forceSnapToStep={true}`, the thumb is not draggable anymore. Am I missing something or is this a bug?

**Comment by romin-backpack** [comment]
Thanks @alantoa there does seem to be another issue though, the markers don't change color when you drag, after you set `forceSnapToStep={true}`. Even when you remove the `useAnimatedReaction` you can still see the markers not changing color. Any idea why this happens?



https://github.com/user-attachments/assets/29cd3f4b-3666-46d6-88b5-a5268d946066

**Comment by alantoa** [comment]
This is a potential bug that I just fixed in [v2.6.2](https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.6.2). You can check the latest example. 

https://github.com/user-attachments/assets/8267b5e8-d87d-4702-98e5-5fa1c0a15fe5

**Comment by DavitVosk** [comment]
Have the same problem when using `forceSnapToStep`. Steps to reproduce:
[] enable forceSnapToStep
[] change slider value just clicking on some area of slider (not sliding the thumb, just click on slider)
[] try changing slider external value

P.S.1 can reproduce the same problem on binance example also
P.S.2 can reproduce the same problem on https://slider.0xalt.xyz/

https://github.com/user-attachments/assets/bd4d96a6-a816-4121-8bc2-a7b8fa46b375

**Comment by DavitVosk** [comment]
Found a solution 🦾: in codes make sure you are setting `isScrubbingInner.value` as a `false` in `onFinalize` of `onSingleTapEvent` function

<img width="637" height="224" alt="Image" src="https://github.com/user-attachments/assets/70f620e6-e9bc-43c0-937e-dfa906d74817" />
