### ISSUE TITLE
Add step color

### ISSUE THREAD

**Issue by masosky** [alantoa/react-native-awesome-slider#88]
It would be awesome to create a slider with different steps colors like
<img width="275" alt="Screenshot 2024-12-22 at 22 15 13" src="https://github.com/user-attachments/assets/7075a026-cdba-4dc2-b53a-3d6a527a64e1" />
Maybe we can provide a new props like renderTrack?

I cna help with the PR if needed.

Xavi

**Comment by alantoa** [comment]
> Maybe we can provide a new props like renderTrack? 

I'd like to add it! 
if you could make a PR for it, that would be great! I can review it, then release a version for you!

**Comment by alantoa** [comment]
@masosky  just added it in [v2.7.2](https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.7.2)! you can refer to [this example](https://github.com/alantoa/react-native-awesome-slider/blob/v2.7.2/example/src/sample/src/with-custom-track.tsx).

![CleanShot 2024-12-24 at 04 37 40](https://github.com/user-attachments/assets/2eba964e-9dc7-4878-8f1c-cc0d67a02ada)

**Comment by masosky** [comment]
Oh sorry I completely forgot about this PR. Thanks a lot!
