### ISSUE TITLE
Implement range

### ISSUE THREAD

**Issue by SohelIslamImran** [alantoa/react-native-awesome-slider#9]
How to use range with two thumbs?

**Comment by alantoa** [comment]
Sorry, currently not supported.

**Comment by SohelIslamImran** [comment]
Do you have any plan to add this? And can you please recommend a package for this?

**Comment by alantoa** [comment]
Hi, No yet, you can try to this https://github.com/miblanchard/react-native-slider

**Comment by SohelIslamImran** [comment]
Thank you. But your package is smoother and faster.

**Comment by alantoa** [comment]
Yaeh, this lib more suitable for video/audio's  scrubber, because they need frequent updates, they need more stability and   smooth.
If your needs are simple,  there will be a lot of libraries available!
